version: '3.1'

services:
  # mongo:
  #   image: mongo:7
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: secret
  #   volumes:
  #     - ./data:/data/db

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
